name: Pull Main Branch

on:
  push:
    branches:
      - main

jobs:
  pull_main_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Call PHP webhook handler
      run: |
        curl -X POST -d '{"secret": "${{ secrets.WEBHOOK_SECRET }}"}' https://accessibility.arthurlecompte.com/webhook.php
