name: Pull Main Branch

on:
  push:
    branches:
      - main

jobs:
  pull_main_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Call PHP webhook handler
      run: |
        curl -X POST -d '{}' https://accessibility.arthurlecompte.com/webhook.php
      env:
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
